set(_CATKIN_CURRENT_PACKAGE "jaist_quad_gui")
set(jaist_quad_gui_MAINTAINER "redwan <redwan@todo.todo>")
set(jaist_quad_gui_DEPRECATED "")
set(jaist_quad_gui_VERSION "0.0.0")
set(jaist_quad_gui_BUILD_DEPENDS "ardrone_autonomy" "cv_bridge" "image_transport" "dynamic_reconfigure" "geometry_msgs" "message_generation" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(jaist_quad_gui_RUN_DEPENDS "ardrone_autonomy" "cv_bridge" "image_transport" "dynamic_reconfigure" "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "std_srvs")
set(jaist_quad_gui_BUILDTOOL_DEPENDS "catkin")